### ISSUE TITLE
FinRL_PaperTrading_Demo.ipynb - errors on trading operation

### ISSUE THREAD

**Issue by marcipops** [AI4Finance-Foundation/FinRL-Meta#226]
**Environment:**
Win10
Chrome
Colab
File at https://colab.research.google.com/github/AI4Finance-Foundation/FinRL-Tutorials/blob/master/3-Practical/FinRL_PaperTrading_Demo.ipynb

No change to this file other than Alpaca credentials required.

**Function call:**
paper_trading_erl = AlpacaPaperTrading(ticker_list = DOW_30_TICKER, 
                                       time_interval = '1Min', 
                                       drl_lib = 'elegantrl', 
                                       agent = 'ppo', 
                                       cwd = './papertrading_erl_retrain', 
                                       net_dim = ERL_PARAMS['net_dimension'], 
                                       state_dim = state_dim, 
                                       action_dim= action_dim, 
                                       API_KEY = API_KEY, 
                                       API_SECRET = API_SECRET, 
                                       API_BASE_URL = API_BASE_URL, 
                                       tech_indicator_list = INDICATORS, 
                                       turbulence_thresh=30, 
                                       max_stock=1e2)
paper_trading_erl.run()

**Error Output**:
load actor from: ./papertrading_erl_retrain/actor.pth
Waiting for market to open...
0 minutes til market open.
Market opened.
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 182, in trade
    state = self.get_state()
  File "<ipython-input-24-90be2ea33e6d>", line 247, in get_state
    tech_indicator_list=self.tech_indicator_list)
  File "/usr/local/lib/python3.7/dist-packages/finrl/meta/data_processors/processor_alpaca.py", line 355, in fetch_latest_data
    raise ValueError
ValueError

Succesfully add technical indicators
Successfully transformed into array
30
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 186, in trade
    s_tensor = torch.as_tensor((state,), device=self.device)
AttributeError: 'AlpacaPaperTrading' object has no attribute 'device'

Succesfully add technical indicators
Successfully transformed into array
30
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 186, in trade
    s_tensor = torch.as_tensor((state,), device=self.device)
AttributeError: 'AlpacaPaperTrading' object has no attribute 'device'

Succesfully add technical indicators
Successfully transformed into array
30
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 186, in trade
    s_tensor = torch.as_tensor((state,), device=self.device)
AttributeError: 'AlpacaPaperTrading' object has no attribute 'device'

Succesfully add technical indicators
Successfully transformed into array
30
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 186, in trade
    s_tensor = torch.as_tensor((state,), device=self.device)
AttributeError: 'AlpacaPaperTrading' object has no attribute 'device'

Succesfully add technical indicators
Successfully transformed into array
30
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-24-90be2ea33e6d>", line 186, in trade
    s_tensor = torch.as_tensor((state,), device=self.device)
AttributeError: 'AlpacaPaperTrading' object has no attribute 'device'

**Comment by marcipops** [comment]
Confirmed that I also get the same error in a local environment (Win10/WSL/Ubuntu20.04/Python 3.8.10) running in Vscode 1.70.2.
Hope that helps.

**Comment by zhumingpassional** [comment]
Thanks for reporting it. 

We are revising the code.

**Comment by marcipops** [comment]
Thanks Ming!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by marcipops** [comment]
Any update on this please Ming?

**Comment by zhumingpassional** [comment]
@marcipops  we will submit PRs.  sorry for delayed update.

**Comment by zhumingpassional** [comment]
updated.
pls test it.

**Comment by marcipops** [comment]
Tested on Colab. Still fails with the same error.

**Comment by ZiyiXia** [comment]
A new version of paper trading demo was just uploaded, please check it out.

**Comment by marcipops** [comment]
@ZiyiXia much appreciated - yes, it seems to work on Colab.

A minor point, but was discussed some weeks ago.  There are lots of orders sent every run() cycle that are invalid i.e. quantity should not be 0.  Example: Quantity is 0, order of | 0 CAT sell | not completed.

I appreciate that this is due to the agent wanting to do "nothing", but it would be better to only issue orders with a valid quantity.  Also, fixing this would make it easier to see the valid orders from the majority of invalid ones :)

I also have the demo also running locally from yesterday in my test environment of Win10 WSL/Ubuntu 20.04, as Ubuntu 20.04 is my target production environment.  Jingyang Rui had a similar environment.  t does have some warnings and exceptions but hasn't crashed (yet).

-------------------------------------------------------------------
The warnings are:

  data_df = data_df.append(barset)
/home/marc/venv/lib/python3.8/site-packages/finrl/meta/data_processors/processor_alpaca.py:301: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
...
/home/marc/venv/lib/python3.8/site-packages/finrl/meta/data_processors/processor_alpaca.py:178: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  indicator_df = indicator_df.append(temp_indicator, ignore_index=True)

-------------------------------------------------------------------
The exceptions are:

Exception in thread Thread-8814:
Traceback (most recent call last):
  File "/home/marc/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/home/marc/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v2/stocks/bars?timeframe=1Min&adjustment=raw&limit=100&symbols=AXP

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_506/4288445362.py", line 182, in trade
  File "/tmp/ipykernel_506/4288445362.py", line 245, in get_state
  File "/home/marc/venv/lib/python3.8/site-packages/finrl/meta/data_processors/processor_alpaca.py", line 298, in fetch_latest_data
    barset = self.api.get_bars([tic], time_interval, limit=limit).df  # [tic]
  File "/home/marc/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 714, in get_bars
    bars = list(self.get_bars_iter(symbol,
  File "/home/marc/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 698, in get_bars_iter
    for bar in bars:
  File "/home/marc/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 585, in _data_get
    resp = self.data_get(path, data=data, feed=feed,
  File "/home/marc/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 270, in data_get
    return self._request(
  File "/home/marc/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 213, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/marc/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 242, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: your subscription does not permit querying data from the past 15 minutes
Exception in thread Thread-8815:
Traceback (most recent call last):
  File "/home/marc/venv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 234, in _one_request
    resp.raise_for_status()
  File "/home/marc/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v2/stocks/bars?timeframe=1Min&adjustment=raw&limit=100&symbols=AXP
