### ISSUE TITLE
Bugs in FinRL-Tutorials

### ISSUE THREAD

**Issue by Tizzzzy** [AI4Finance-Foundation/FinRL-Meta#335]
The bug is in [FinRL-Tutorial 1-Introduction Stock_NeurIPS2018_1_Data.ipynb
](https://github.com/AI4Finance-Foundation/FinRL-Tutorials/blob/master/1-Introduction/Stock_NeurIPS2018/Stock_NeurIPS2018_1_Data.ipynb)
## Environment 
`python`: 3.7.16; `swig`: 4.2.1; `wrds`: 3.1.6; `pyportfolioopt`: 0.3.2

After I ran cell 1, cell 2 requires me to download more package including `yfinance`, `finrl`, `gymnasium`, `stable-baselines3[extra]`, `exchange-calendars`

After I pip install all those packages, I got this error:

```bash
Traceback (most recent call last):

  File "c:\Users\super\anaconda3\envs\ai4finance\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "C:\Users\super\AppData\Local\Temp\ipykernel_36104\1185721934.py", line 7, in <module>
    from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split

  File "c:\Users\super\anaconda3\envs\ai4finance\lib\site-packages\finrl\meta\preprocessor\preprocessors.py", line 10, in <module>
    from finrl import config

  File "c:\Users\super\anaconda3\envs\ai4finance\lib\site-packages\finrl\__init__.py", line 5, in <module>
    from finrl.train import train

  File "c:\Users\super\anaconda3\envs\ai4finance\lib\site-packages\finrl\train.py", line 10, in <module>
    from finrl.meta.data_processor import DataProcessor

  File "c:\Users\super\anaconda3\envs\ai4finance\lib\site-packages\finrl\meta\data_processor.py", line 7, in <module>
    from finrl.meta.data_processors.processor_wrds import WrdsProcessor as Wrds

  File "c:\Users\super\anaconda3\envs\ai4finance\lib\site-packages\finrl\meta\data_processors\processor_wrds.py", line 9, in <module>
    import wrds

  File "c:\Users\super\anaconda3\envs\ai4finance\lib\site-packages\wrds\__init__.py", line 33, in <module>
    from .sql import Connection
...
  File "<fstring>", line 1
    (err=)
        ^
SyntaxError: invalid syntax
```

**Comment by laion01** [comment]
> we will recruit new research assistants to join us and help maintain the project.

Are you still working on this project? I'm really interested but cannot run
